### ISSUE TITLE
Initial guess does not work with AMCL

### ISSUE THREAD

**Issue by barbalberto** [robotology/navigation#22] opened 2019-07-08 09:37 UTC
When starting the navigation, the procedure requires to give an initial guess to the AMCL ROS localizer is hard to start correctly. The result is that some day it works, some other day it doesn; t start at all.

This needs to be fixed because people wants to use the robot, but then they have to give up because navigation does not start.

**Comment by randaz81** [comment] 2019-07-08 14:03
Thank you for reporting this.
The issue is currently under investigation: https://github.com/hsp-iit/project-mobile-actions/issues/78

**Comment by randaz81** [comment] 2019-07-10 14:49
covariance matrix fixed by: https://github.com/robotology/navigation/commit/ff7bd5cf6aa175cf9c8884e33c23c83e443b1ea7
I'm still not sure if the bug is fixed or not...

**Comment by randaz81** [comment] 2020-01-15 18:26
Fixed by https://github.com/robotology/navigation/commit/ff7bd5cf6aa175cf9c8884e33c23c83e443b1ea7

**Closed by randaz81** 2020-01-15 18:26 UTC
Labels: bug
